### ISSUE TITLE
没抓到具体的崩溃

### ISSUE THREAD

**Issue by jin123d** [simplepeng/SpiderMan#31]
崩溃没有抓包具体的崩溃，显示`CrashActivity`种的`NullPointerException`

```

07-02 14:35:17.960 24538 24538 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.buli/com.simple.spiderman.CrashActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
--
21007-02 14:35:17.960 24538 24538 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4289)
21107-02 14:35:17.960 24538 24538 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4437)
21207-02 14:35:17.960 24538 24538 E AndroidRuntime: at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
21307-02 14:35:17.960 24538 24538 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
21407-02 14:35:17.960 24538 24538 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
21507-02 14:35:17.960 24538 24538 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2829)
21607-02 14:35:17.960 24538 24538 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:108)
21707-02 14:35:17.960 24538 24538 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:226)
21807-02 14:35:17.960 24538 24538 E AndroidRuntime: at android.os.Looper.loop(Looper.java:328)
21907-02 14:35:17.960 24538 24538 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:9182)
22007-02 14:35:17.960 24538 24538 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
22107-02 14:35:17.960 24538 24538 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
22207-02 14:35:17.960 24538 24538 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
22307-02 14:35:17.960 24538 24538 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
22407-02 14:35:17.960 24538 24538 E AndroidRuntime: at java.lang.String.valueOf(String.java:4092)
22507-02 14:35:17.960 24538 24538 E AndroidRuntime: at java.lang.StringBuilder.append(StringBuilder.java:179)
22607-02 14:35:17.960 24538 24538 E AndroidRuntime: at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:727)
22707-02 14:35:17.960 24538 24538 E AndroidRuntime: at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:735)
22807-02 14:35:17.960 24538 24538 E AndroidRuntime: at java.lang.Throwable.printStackTrace(Throwable.java:697)
22907-02 14:35:17.960 24538 24538 E AndroidRuntime: at java.lang.Throwable.printStackTrace(Throwable.java:753)
23007-02 14:35:17.960 24538 24538 E AndroidRuntime: at android.util.Log.getStackTraceString(Log.java:388)
23107-02 14:35:17.960 24538 24538 E AndroidRuntime: at com.simple.spiderman.CrashActivity.onCreate(CrashActivity.java:59)
23207-02 14:35:17.960 24538 24538 E AndroidRuntime: at android.app.Activity.performCreate(Activity.java:8942)
23307-02 14:35:17.960 24538 24538 E AndroidRuntime: at android.app.Activity.performCreate(Activity.java:8906)
23407-02 14:35:17.960 24538 24538 E AndroidRuntime: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
23507-02 14:35:17.960 24538 24538 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4265)
23607-02 14:35:17.960 24538 24538 E AndroidRuntime: ... 12 more


```

**Comment by simplepeng** [comment]
@jin123d 试试`v1.2.0`新版
